[toolchain]
anchor = "0.29.0"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://github.com/raydium-io/raydium-cpi"

[provider]
cluster = "Localnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
